### ISSUE TITLE
Create an action to export pivot contents to Excel

### ISSUE THREAD

**Issue by glaschenko** [cuba-platform/charts#28]
Current way of CSV copy-paste is very clumsy.

----
### Description
Created extension for `PivotTable` component - `PivotTableExtension`. It is not a component and can't be created in `ComponentsFactory`.

Given extension provides API for downloading PivotTable with aggregated data to excel with `*.xls` format.

**Note**, the extension works only for the following renderers types: "Table", "Table Barchart", "Heatmap", "Row Heatmap", "Col Heatmap". And doesn't get the color of cells.

In `PivotTableExtension` interface we have two methods for downloading file:
```
void exportTableToXls();
void exportTableToXls(ExportDisplay display);
```
If it is neccessary to define file name we can use following method:
```
void setFileName(String fileName);
```
**If file name is not defined** it will use localized caption of entity in `PivotTable`

At the server side we can get JSON representation of PivotTable with data or serialized object (`PivotData`):
```
String getPivotDataJSON();
PivotData getPivotData();
```
**Note**, if PivotTable contains more than 65536 rows (XLS doesn't support more rows) content will be cut by the last row and you will see a warning message.

### How to use
In screen controller we should create an instance of extension. And, for example, create method `save()`, that will be invoked from some button;
```
@Inject
private PivotTable pivotTable;

private PivotTableExtension extension;

@Override
public void init(Map<String, Object> params) {
    extension = new WebPivotTableExtension(pivotTable);
}

public void save() {
    extension.exportTableToXls();
}
```
XML:
```
<layout expand="pivotTable">
    <button caption="download" invoke="save"/>
    <chart:pivotTable id="pivotTable"
                      autoSortUnusedProperties="true"
                      datasource="tipsDs"
                      editable="true">
        <chart:properties>
            <chart:property name="row"/>
            <chart:property name="totalBill"/>
            <chart:property name="tip"/>
            <chart:property name="sex"/>
            <chart:property name="smoker"/>
            <chart:property name="day"/>
            <chart:property name="time"/>
            <chart:property name="size"/>
        </chart:properties>

      . . .

    </chart:pivotTable>
</layout>
```
### For QA
Test cases:
1. Check all browsers: IE 9 and 10 (for 6.10), IE 11, Edge, Chrome, FireFox, Safari, (also, Safari iOS);
2. Check file name and default file name;
3. Check warning notification if pivot data rows more than 65536;
4. Check supported renderes type;
5. Check an exception if renderer type is not supported;
6. In the file check that numeric type is numeric and string is string;
7. Try with editable and not editable pivotTable;
8. Check MS Excel in our Dell notebook (Ru and En). Check types of cells (numbers are numbers, strings are strings)
Also, try your test cases.

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[d532f5e4](https://git.haulmont.com/platform/charts/commit/d532f5e4385b3fb9c1e72bfade684f95098e4e03) in **release_6_10** - Create an action to export pivot contents to Excel #28

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[7dc84460](https://git.haulmont.com/platform/charts/commit/7dc84460f72ecac393eadb7c720856db4fbb221e) in **release_6_10** - Create an action to export pivot contents to Excel (javaDoc fix) #28

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[198235c4](https://git.haulmont.com/platform/charts/commit/198235c4779897bb0bfe0fcd3963d67b96a9c141) in **master** - Create an action to export pivot contents to Excel #28

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[54f845e3](https://git.haulmont.com/platform/charts/commit/54f845e3c1457ddcae6dd88d2d981bc4bc44dc0f) in **release_6_10** - Create an action to export pivot contents to Excel (fixes) #28

Fixed update json for non-editable pivotTable and check for
not supported renderes type

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[f7851adb](https://git.haulmont.com/platform/charts/commit/f7851adb22fcf7842d6afb5a5b62111a1b93d312) in **release_6_10** - Create an action to export pivot contents to Excel #28

Fixed renderer configuration from native json, default file name,
set exception without localized message

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[c1c12ac8](https://git.haulmont.com/platform/charts/commit/c1c12ac825d4da1c364f72ec23cbcf8f46985c53) in **master** - Create an action to export pivot contents to Excel #28

Fixed renderer configuration from native json, default file name,
set exception without localized message

**Comment by myatlevEvg** [comment]
Reopen.

**First issue:**
In the Libre Office and Microsoft office cells in a file has the wrong type. In Libre office, every cell has the numeric format. In Microsoft office, every cell has the generic format.

**Second issue:**
1) Use JSON representation in the controller of the screen.
2) Set in xml descriptor some not unsupported renderer type
3) In the controller of the screen in setNativeJson() set some not correct renderer type 

**AR**
Pivot table has been converted to table but can't be downloaded because of IllegalStateException

**Third issue:**
In the case when the pivot table has no datasource downloaded xls file contains two cells - "Total" and "0".
Will be great if in this case platform will be shown warning "No data in pivot table" and does not provide a download.

**Fourth issue:**
xls file downloaded through firefox has no string cells, only numbers
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/4ccb0419-4c8e-4fbe-9827-9d7b0f93f030)

In IE11 xls file can't be downloaded because of exception
```
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.haulmont.charts.web.gui.components.pivottable.PivotExcelExporter.createRows(PivotExcelExporter.java:168)
	at com.haulmont.charts.web.gui.components.pivottable.PivotExcelExporter.exportPivotTable(PivotExcelExporter.java:104)
	at com.haulmont.charts.web.gui.components.pivottable.WebPivotTableExtension.exportTableToXls(WebPivotTableExtension.java:52)
	at com.haulmont.refapp.web.ui.pivot.PivotSampleScreen.pivotSlap(PivotSampleScreen.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.gui.xml.DeclarativeAction.actionPerform(DeclarativeAction.java:93)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:47)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:71)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:312)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:203)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:412)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1385)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[cea3faae](https://git.haulmont.com/platform/charts/commit/cea3faae9e8ab8f15c32af80a3d83a8d98a0646c) in **release_6_10** - Create an action to export pivot contents to Excel #28

Fixed no data in headers from Firefox, if no data show warning message

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[d0ba1d93](https://git.haulmont.com/platform/charts/commit/d0ba1d939d3eec86864549e1ef47da21df1f7908) in **master** - Create an action to export pivot contents to Excel #28

Fixed no data in headers from Firefox, if no data show warning message
