### ISSUE TITLE
ShowPivotAction should support id property

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/charts#65]
### Environment
- Platform version: 6.10
- Client type: Web
### Description of the bug or enhancement
Support id property. It should be added using `withAdditionalProperties()`.

### Changes
`ShowPivotAction' supports properties that marked as `@id`.

### How to test
Downoload demo project: 
[pivotAction.zip](https://github.com/cuba-platform/charts/files/2599187/pivotAction.zip)

Check screens:
- `String Entities`
- `Int Entitites`
- `Long Id Entities`

1. Click button "Show Pivot"
2. In PivotTable must be id property

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[fa65681d](https://git.haulmont.com/platform/charts/commit/fa65681d5fba7ac4800b276d7ae048f2066919fc) in **release_6_10** - ShowPivotAction should support id property #65

**Comment by haulmont-git** [comment]
Git changesets by `pinyazhin`: 

[c8acf622](https://git.haulmont.com/platform/charts/commit/c8acf62215d5e928517abe78c186cbbb48da3a13) in **master** - ShowPivotAction should support id property #65

**Comment by natfirst** [comment]
In 7.0:
```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.haulmont.cuba.gui.Notifications' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1646)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1205)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166)
	at com.haulmont.cuba.core.sys.CubaDefaultListableBeanFactory.resolveDependency(CubaDefaultListableBeanFactory.java:59)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:668)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:338)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:209)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1095)
	at com.haulmont.cuba.core.sys.BeanLocatorImpl.getPrototype(BeanLocatorImpl.java:79)
	at com.haulmont.cuba.core.global.AppBeans.getPrototype(AppBeans.java:75)
	at com.haulmont.charts.web.gui.components.pivottable.WebPivotTableExtension.<init>(WebPivotTableExtension.java:37)
	at com.haulmont.charts.web.ui.PivotTableScreen.init(PivotTableScreen.java:53)
	at com.haulmont.cuba.gui.components.AbstractWindow.init(AbstractWindow.java:94)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:125)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:53)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:220)
	at com.haulmont.cuba.web.sys.WebScreens.openWindow(WebScreens.java:990)
	at com.haulmont.charts.gui.components.action.ShowPivotAction.showPivotTable(ShowPivotAction.java:161)
	at com.haulmont.charts.gui.components.action.ShowPivotAction.actionPerform(ShowPivotAction.java:125)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:61)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```
